#!/bin/bash

i3_path="i3/.config/i3/"
zsh_path="zsh/.zsh_conf"
dot_path="$HOME/.cargo/bin/dot"

hname=$(hostname)
os=$(uname -s)

pre_linux() {
	# prepare dunst
	mkdir -p .config/dunst/

	# merge i3 config with chosen
	cat $i3_path/config.base > $i3_path/config

	# append per pc config
	cat $i3_path/config.$hname >> $i3_path/config

	# append common
	cat $i3_path/config.common >> $i3_path/config
}

pre_macos() {
	:
	# nop
}

case "${os}" in
    Linux*)     pre_linux;;
    Darwin*)    pre_macos;;
    *)          echo "Unknown OS"; exit 1
esac

# check if pretzo is installed, if not, install it now
[ ! -d "${ZDOTDIR:-$HOME}/.zprezto" ] && git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

# check dot is installed
[ ! -f "$dot_path" ] && { echo "dot is not installed."; exit 1; }

# configure and install zsh configs
cat $zsh_path/zshenv.all > zsh/.zshenv
cat $zsh_path/zshenv.$hname >> zsh/.zshenv

$dot_path link

post_linux() {
	$HOME/.config/rofi/themeswitch.sh island-flow.png
	i3-msg restart
}

post_macos() {
	:
}

case "${os}" in
    Linux*)     post_linux;;
    Darwin*)    post_macos;;
    *)          echo "Unknown OS"; exit 1
esac

