#!/bin/bash

i3_path="i3/.config/i3/"
zsh_path="zsh/.zsh_conf"

# prepare dunst
mkdir -p .config/dunst/

# merge i3 config with chosen
cat $i3_path/config.base > $i3_path/config

# check if pretzo is installed, if not, install it now
[ ! -d "${ZDOTDIR:-$HOME}/.zprezto" ] && git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

if [[ "$1" == "desktop" ]]; then
	echo "Deploying desktop configuration"
	cat $i3_path/config.desktop >> $i3_path/config
	cat $zsh_path/zshenv.all > zsh/.zshenv
	cat $zsh_path/zshenv.desktop >> zsh/.zshenv
elif [[ "$1" == "laptop" ]]; then
	echo "Deploying laptop configuration"
	cat $i3_path/config.laptop >> $i3_path/config
	cat $zsh_path/zshenv.all > zsh/.zshenv
	cat $zsh_path/zshenv.laptop >> zsh/.zshenv
else
	echo "Missing deploy type, either desktop or laptop"
	exit 1
fi

find . -maxdepth 1 -name "[!.]*" -type d -exec bash -c 'stow -R $(basename "$0")' {} \;

$HOME/.config/rofi/themeswitch.sh island-flow.png

i3-msg restart