#!/bin/zsh

VMS_RUNNING=$(virsh -c qemu:///system list --name | wc -l)
BACKUP_IN_PROGRESS=$(pgrep $HOME/scripts/backup/borg_backup | wc -l)


pre_script() {
	if [ $VMS_RUNNING -gt 1 ]; then
	    notify-send "Failed to $1" "Virtual machines are stilling running." --icon=dialog-warning
	    exit 1
	fi
	if [ $BACKUP_IN_PROGRESS -gt 0 ]; then
	    notify-send "Failed to $1" "Backup is in progress" --icon=dialog-warning
	    exit 1
	fi
}

echo $1

case "$1" in
    lock)
        $HOME/.config/i3/scripts/customlock.sh
        ;;
    reboot)
		pre_script $1
		notify-send "Rebooting..." "Bye Bye" --icon=dialog-warning
		loginctl reboot
        ;;
    shutdown)
		pre_script $1
		notify-send "Shutting down..." "Bye Bye" --icon=dialog-warning
		loginctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|reboot|shutdown}"
        exit 2
esac

