#!/bin/zsh

VMS_RUNNING=$(virsh -c qemu:///system list --name | wc -l)


pre_script() {
	if [ $VMS_RUNNING -gt 1 ]; then
	    notify-send "Failed to $1" "Virtual machines are stilling running." --icon=dialog-warning
	    exit 1
	fi
}

echo $1

case "$1" in
    lock)
        $HOME/.config/i3/scripts/customlock.sh
        ;;
    reboot)
		pre_script $1
		notify-send "Rebooting..." "Bye Bye" --icon=dialog-warning
        #dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" \
        #/org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Restart
	#dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Restart
	dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.Reboot" boolean:true
        ;;
    shutdown)
		pre_script $1
		notify-send "Shutting down..." "Bye Bye" --icon=dialog-warning
        #dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" \
        #/org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Stop
	dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.PowerOff" boolean:true
        ;;
    *)
        echo "Usage: $0 {lock|reboot|shutdown}"
        exit 2
esac

