#!/bin/bash

VMS_RUNNING=$(virsh -c qemu:///system list --name | wc -l)

echo $VMS_RUNNING
if [ $VMS_RUNNING -gt 1 ]; then
    notify-send "Failed to shutdown" "Virtual machines are stilling running." --icon=dialog-warning
    exit 1
else
    notify-send "Shutting down" "Bye Bye" --icon=dialog-warning
    dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" \
	/org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Stop
fi
