#!/bin/bash

set $BLOCK_INSTANCE

NAME=$1
MAC=$2
if [[ $BLOCK_BUTTON == 1 ]]; then
  if [[ $(echo -e 'info' | bluetoothctl) != *"$NAME"* ]]; then
    # Not connected.. Connect now
    $(echo -e "connect $MAC" | bluetoothctl)
  else
    # Already connected, Disconnect
    $(echo -e "disconnect" | bluetoothctl)
  fi
fi

COLOR=\#FF0000
TEXT="OFF"
if [[ $(echo -e 'info' | bluetoothctl) == *"$NAME"* ]]; then
  COLOR=\#00FF00
  TEXT="ON"
fi

echo "$TEXT"
echo "$TEXT"
echo $COLOR
exit 0
